services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: notifier.settings.test
    depends_on: !reset []

  worker:
    environment:
      DJANGO_SETTINGS_MODULE: notifier.settings.test
    depends_on: !reset []

  beat:
    environment:
      DJANGO_SETTINGS_MODULE: notifier.settings.test
    depends_on: !reset []

  db:
    ports: !reset []

  redis:
    ports: !reset []

  mailpit:
    ports: !reset []
